baseURL: https://ravencole.com/
languageCode: en-us
title: "Raven Cole"
theme: tale

author:
  name: "Raven Cole"

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0
